trigger:
  branches:
    include:
      - main
      - dev

stages:
  - stage: Dev
    displayName: Deploy to DEV
    jobs:
      - deployment: DeployToDev
        environment: 'DEV'
        strategy:
          runOnce:
            deploy:
              steps:
                - script: echo "Deploying to DEV"
                  displayName: "DEV Stage"

  - stage: Test
    displayName: Deploy to TEST
    dependsOn: Dev
    jobs:
      - deployment: DeployToTest
        environment: 'TEST'
        strategy:
          runOnce:
            deploy:
              steps:
                - script: echo "Running tests in TEST"
                  displayName: "TEST Stage"

  - stage: UAT
    displayName: Deploy to UAT
    dependsOn: Test
    jobs:
      - deployment: DeployToUAT
        environment: 'UAT'
        strategy:
          runOnce:
            deploy:
              steps:
                - script: echo "User acceptance testing in UAT"
                  displayName: "UAT Stage"

  - stage: Prod
    displayName: Deploy to PROD
    dependsOn: UAT
    jobs:
      - deployment: DeployToProd
        environment: 'PROD'
        strategy:
          runOnce:
            deploy:
              steps:
                - script: echo "Production deployment!"
                  displayName: "PROD Stage"
